# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMS-Mollie
version:      0.02
version_from: lib/Net/SMS/Mollie.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::Simple:                  0.44
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
